# 服务器的配置项
server:
  port: 18087
  servlet:
    context-path: /mall-gateway

spring:
  # Application 的配置项
  application:
    name: mall-gateway
  # SpringMVC 配置项
  mvc:
    throw-exception-if-no-handler-found: true # 匹配不到路径时，抛出 NoHandlerFoundException 异常
    static-path-pattern: /doc.html # 静态资源的路径
