spring:
  profiles:
    active: local

# Dubbo 配置项
dubbo:
  # Spring Cloud Alibaba Dubbo 专属配置
  cloud:
    subscribed-services: 'system-service' # 设置订阅的应用列表，默认为 * 订阅所有应用
  # Dubbo 服务消费者的配置
  consumer:
    timeout: 10000
    validation: true # 开启 Consumer 的参数校验
    check: false # 本地启动，不进行校验，不一定会使用到未启动的服务，嘿嘿~
    UserSmsCodeRpc:
      version: 1.0.0
    UserRpc:
      version: 1.0.0
    OAuth2Rpc:
      version: 1.0.0
    SystemAccessLogRpc:
      version: 1.0.0
    SystemExceptionLogRpc:
      version: 1.0.0
    UserAddressRpc:
      version: 1.0.0